import React from 'react'
import { useNavigate } from 'react-router-dom'
import { cn } from '@/shared/utils'
import { useFolder } from '@/queries/folder-queries'
import { useNotesByFolder } from '@/queries/note-queries'
import { useCreateFolder, useDeleteFolder } from '@/mutations/folder-mutations'
import { useCreateNote, useDeleteNote } from '@/mutations/note-mutations'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Separator } from '@/components/ui/separator'
import { Skeleton } from '@/components/ui/skeleton'
import { useToast } from '@/components/ui/use-toast'
import type { TFolder, TNote, TWorkspaceItem } from '@/domain/entities/workspace'

// ... rest of the file content ... 